name: Openwrt Build
on:
  workflow_dispatch: 
    inputs:
      target:
        description: '目标设备'
        required: true
        default: 'vplus' 
        type: choice
        options:
        - vplus
        - beikeyun
        - l1pro 
        - rock5b
        - h88k
        - r66s 
        - r68s
        - h68k
        - e25 
        - s905
        - s905d
        - s905x2 
        - s905x3
        - s912
        - s922x 
        - s922x-n2 
        - qemu
        - r3g
        - r3p
        - rm2100
      config:
        description: '插件配置'
        required: true
        default: 'armv8'
        type: choice
        options:
        - armv8
        - r3g
        - r3p
        - rm2100
        - simple

jobs:
  build:
    name: Openwrt Build For ${{ inputs.target }}
    #runs-on: ubuntu-20.04
    runs-on: self-hosted
    steps:
      - name: Checkout package script
        uses: actions/checkout@v2.5.0
        with:
          path: package_scirpt

      - name: Build openwrt
        run: sudo ./run_build_use_docker.sh -c ${{ inputs.config }} -d ${{ inputs.target }}
        working-directory: package_scirpt

      - name: Set artifact
        run: |
          ARTIFACT_PATH=$(ls package_scirpt/openwrt_build_tmp/artifact/*/*.7z)
          echo "ARTIFACT_PATH=$ARTIFACT_PATH" >> $GITHUB_ENV
          echo "ARTIFACT_FILE=$(basename $ARTIFACT_PATH)" >> $GITHUB_ENV
        working-directory: ./

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: ${{ env.ARTIFACT_FILE }}
          path: package_scirpt/${{ env.ARTIFACT_PATH }}
          retention-days: 2
