name: Openwrt Build
on:
  workflow_dispatch: 
    inputs:
      target:
        description: '目标设备'
        required: true
        default: 'x86' 
        type: choice
        options:
        - x86
        - vplus
        - beikeyun
        - l1pro 
        - rock5b
        - h88k
        - r66s 
        - r68s
        - h68k
        - e25 
        - s905
        - s905d
        - s905x2 
        - s905x3
        - s912
        - s922x 
        - s922x-n2 
        - qemu
        - r3g
        - r3p
        - rm2100
      config:
        description: '插件配置'
        required: true
        default: 'x86_64'
        type: choice
        options:
        - x86_64
        - armv8
        - armv8_full
        - r3g
        - r3p
        - rm2100
        - armv8_simple
      useLatestCode:
        description: '使用最新源代码编译'
        required: true
        type: boolean
        default: false
      useSelfHosted:
        description: '使用自建机器编译（需配置Runner）'
        required: true
        type: boolean
        default: false
      useCache:
        description: '使用编译缓存进行加速（仅自建机器下生效）'
        required: true
        type: boolean
        default: false
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      config:
        required: true
        type: string
      useSelfHosted:
        required: false
        type: boolean
        default: false
      useLatestCode:
        required: false
        type: boolean
        default: true
      useCache:
        required: false
        type: boolean
        default: false
    outputs:
        OPENWRT_VER:
          description: "使用的lede仓库源码版本"
          value: ${{ jobs.build.outputs.OPENWRT_VER }}
        OPENWRT_COMMIT_ID:
          description: "使用的lede仓库源码提交点"
          value: ${{ jobs.build.outputs.OPENWRT_COMMIT_ID }}
        OPENWRT_PACKAGES_COMMIT_ID:
          description: "使用的PACKAGES插件库源码提交点"
          value: ${{ jobs.build.outputs.OPENWRT_PACKAGES_COMMIT_ID }}
        PASSWALL_PACKAGE_COMMIT_ID:
          description: "使用的PASSWALL插件库源码提交点"
          value: ${{ jobs.build.outputs.PASSWALL_PACKAGE_COMMIT_ID }}
        SMALL_PACKAGE_COMMIT_ID:
          description: "使用的SMALL插件库源码提交点"
          value: ${{ jobs.build.outputs.SMALL_PACKAGE_COMMIT_ID }}
jobs:
  build:
    name: ${{ inputs.target }}_${{ inputs.config }}
    #runs-on: ubuntu-20.04 github action免费的机器配置有限，容易导致编译失败，建议自己配个runner，配置要求硬盘空闲容量有50G以上，并装好docker，支持访问外网即可，建议使用ubuntu-20.04系统
    runs-on: ${{ inputs.useSelfHosted && 'self-hosted' || 'ubuntu-20.04' }}
    timeout-minutes: 2880
    outputs: 
      OPENWRT_VER: ${{ steps.version.outputs.OPENWRT_VER }} 
      OPENWRT_COMMIT_ID: ${{ steps.version.outputs.OPENWRT_COMMIT_ID }}
      OPENWRT_PACKAGES_COMMIT_ID: ${{ steps.version.outputs.OPENWRT_PACKAGES_COMMIT_ID }} 
      PASSWALL_PACKAGE_COMMIT_ID: ${{ steps.version.outputs.PASSWALL_PACKAGE_COMMIT_ID }} 
      SMALL_PACKAGE_COMMIT_ID: ${{ steps.version.outputs.SMALL_PACKAGE_COMMIT_ID }} 
    env:
      package_build_tool_path: 'source' # 存放本项目工具的目录名称
      compile_path: 'compile_dir' # 存放编译过程产物及产出物的目录名称
      container_name: 'GithubActionBuild_${{ github.run_number }}' # 编译时使用的容器名
    steps:
      - id: version
        name: Output version
        if: success()
        run: |
          echo "OPENWRT_VER=R23.04.13" >> $GITHUB_OUTPUT
          echo "OPENWRT_COMMIT_ID=8f42e0d971265c055eb2ccda5a683143d3ca10cb" >> $GITHUB_OUTPUT
          echo "OPENWRT_PACKAGES_COMMIT_ID=a5d2dbf6c97dedbf454dba7f267d917c05f5095e" >> $GITHUB_OUTPUT
          echo "PASSWALL_PACKAGE_COMMIT_ID=2c35b6f2cf898d9ffcf4f7876319a911da67b124" >> $GITHUB_OUTPUT
          echo "SMALL_PACKAGE_COMMIT_ID=894ef300c3c4e262f202c21ec688ed3ba65e9ab8" >> $GITHUB_OUTPUT
   #     working-directory: ${{ env.compile_path }}
