---
name: Openwrt Build

on:
  workflow_dispatch: 
    inputs:
      target:
        description: '目标设备'
        required: true
        default: 'r3g' 
        type: choice
        options:
        - vplus
        - beikeyun
        - l1pro 
        - rock5b
        - h88k
        - r66s 
        - r68s
        - h68k
        - e25 
        - s905
        - s905d
        - s905x2 
        - s905x3
        - s912
        - s922x 
        - s922x-n2 
        - qemu
        - r3g
        - r3p
        - rm2100
      config:
        description: '插件配置'
        required: true
        default: 'r3g'
        type: choice
        options:
        - armv8
        - r3g
        - r3p
        - rm2100
        - simple

jobs:
  build:
    name: Openwrt Build For ${{ inputs.target }}
    runs-on: ubuntu-latest
    container: codercai/openwrt_package
    steps:
      - name: Checkout package script
        uses: actions/checkout@v2.5.0
        with:
          path: package_scirpt
    
      - name: Set openwrt version
        run: |
          OPENWRT_VERSION_FILE=build_openwrt_version
          if [ -f "$OPENWRT_VERSION_FILE" ] && [ -s "$OPENWRT_VERSION_FILE" ]
          then
              OPENWRT_VER=$(cut -d ':' -f 1 "$OPENWRT_VERSION_FILE")
              OPENWRT_COMMIT_ID=$(cut -d ':' -f 2 "$OPENWRT_VERSION_FILE")
          else
              OPENWRT_VER=R$(TZ=':Asia/Shanghai' date '+%y.%m.%d')
              OPENWRT_COMMIT_ID="master"
          fi
          echo "OPENWRT_VER=R$OPENWRT_VER" >> $GITHUB_ENV
          echo "OPENWRT_COMMIT_ID=$OPENWRT_COMMIT_ID" >> $GITHUB_ENV
          echo '当前选择OP时间版本为：'$OPENWRT_VER
          echo '当前选择OP的CommitId为：'$OPENWRT_COMMIT_ID
        working-directory: package_scirpt
    
      - name: Checkout openwrt
        uses: actions/checkout@v2.5.0
        with:
          path: openwrt
          repository: coolsnowwolf/lede
          ref: ${{ env.OPENWRT_COMMIT_ID }}

      - name: Copy config
        run: cp ./configs/${{ inputs.config }}.config openwrt/.config
        working-directory: package_scirpt

      - name: Download lib
        run: make download -j$((`nproc` + 1))
        working-directory: openwrt
      
      - name: Build openwrt
        run:  make -j$((`nproc` + 1)) ||  make V=s -j1
        working-directory: openwrt

      - name: Package Armvirt as OpenWrt
        uses: unifreq/openwrt_packit@master
        if: (github.event.inputs.config == 'armv8')
        env:
          OPENWRT_ARMVIRT: openwrt/bin/targets/*/*/*.tar.gz
          PACKAGE_SOC: ${{ inputs.target }}
          KERNEL_VERSION_NAME: 6.1.1
          WHOAMI: 菜头君
          SW_FLOWOFFLOAD: 0
          SFE_FLOW: 0
          ENABLE_WIFI_K504: 0
          ENABLE_WIFI_K510: 0
          OPENWRT_VER: ${{ env.OPENWRT_VER }}

      - name: Upload armvirt built artifacts
        if: (github.event.inputs.config == 'armv8')
        uses: actions/upload-artifact@v3.1.1
        with:
          name: ${{ env.OPENWRT_VER }}_${{ inputs.target }}.zip
          path: ${{ env.PACKAGED_OUTPUTPATH }}/*
          retention-days: 2

      - name: Upload route built artifacts
        if: (github.event.inputs.config != 'armv8')
        uses: actions/upload-artifact@v3.1.1
        with:
          name: ${{ env.OPENWRT_VER }}_${{ inputs.target }}.zip
          path: openwrt/bin/targets/ramips/*/*.bin
          retention-days: 2
