name: Openwrt Build
on:
  workflow_dispatch: 
    inputs:
      target:
        description: '目标设备'
        required: true
        default: 'vplus' 
        type: choice
        options:
        - vplus
        - beikeyun
        - l1pro 
        - rock5b
        - h88k
        - r66s 
        - r68s
        - h68k
        - e25 
        - s905
        - s905d
        - s905x2 
        - s905x3
        - s912
        - s922x 
        - s922x-n2 
        - qemu
        - r3g
        - r3p
        - rm2100
      config:
        description: '插件配置'
        required: true
        default: 'armv8'
        type: choice
        options:
        - armv8
        - r3g
        - r3p
        - rm2100
        - simple
      useCache:
        description: '使用上一次编译缓存进行加速'
        required: true
        type: boolean
        default: true
      useLatestCode:
        description: '使用最新源代码编译'
        required: true
        type: boolean

jobs:
  build:
    name: Openwrt Build For ${{ inputs.target }}
    #runs-on: ubuntu-20.04 github action免费的机器配置有限，容易导致编译失败，建议自己配个runner，配置要求硬盘空闲容量有50G以上，并装好docker，支持访问外网即可，建议使用ubuntu-20.04系统
    runs-on: self-hosted
    steps:
      - name: Clean source
        run: sudo rm -rf ./source

      - name: Clean environment
        if:  ${{ !inputs.useCache }} 
        run: sudo rm -rf ./compile_dir

      - name: Checkout source
        uses: actions/checkout@v2.5.0
        with:
          path: source

      - name: Set use latest
        if:  ${{ inputs.useLatestCode }} 
        run: sudo rm -rf version.sh
        working-directory: source

      - name: Build openwrt
        run: sudo ./run_build_use_docker.sh -c ${{ inputs.config }} -d ${{ inputs.target }} -n "GithubAction_${{ env.GITHUB_RUN_ID}" -o ${{ env.GITHUB_WORKSPACE }}/compile_dir
        working-directory: source

      - name: Set artifact
        run: |
          ARTIFACT_PATH=$PWD/$(ls openwrt_build_tmp/artifact/*/*.7z)
          echo "ARTIFACT_PATH=$ARTIFACT_PATH" >> $GITHUB_ENV
          echo "ARTIFACT_FILE=$(basename $ARTIFACT_PATH)" >> $GITHUB_ENV
        working-directory: compile_dir

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: ${{ env.ARTIFACT_FILE }}
          path: ${{ env.ARTIFACT_PATH }}
          retention-days: 3
