---
name: Openwrt Build

on:
  workflow_dispatch: 
    inputs:
      target:
        description: '目标设备'
        required: true
        default: 'vplus' 
        type: choice
        options:
        - vplus
        - beikeyun
        - l1pro 
        - rock5b
        - h88k
        - r66s 
        - r68s
        - h68k
        - e25 
        - s905
        - s905d
        - s905x2 
        - s905x3
        - s912
        - s922x 
        - s922x-n2 
        - qemu
        - r3g
        - r3p
        - rm2100
      config:
        description: '插件配置'
        required: true
        default: 'armv8'
        type: choice
        options:
        - armv8
        - r3g
        - r3p
        - rm2100
        - simple

jobs:
  build:
    name: Openwrt Build For ${{ inputs.target }}
    runs-on: ubuntu-20.04
    steps:
      - name: Initialization environment
        run: sudo -E apt-get install docker.io
    
      - name: Build openwrt
        run: sudo ./run_build_use_docker.sh -c ${{ inputs.config }} -d ${{ inputs.target }}
        working-directory: package_scirpt

      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.1
        with:
          name: R${{ env.OPENWRT_VER }}_${{ inputs.target }}.7z.zip
          path: package_scirpt/openwrt_build_tmp/artifact/*.7z
          retention-days: 2
