name: Openwrt Build Schedule
on:
  workflow_dispatch: 
  schedule:
    - cron: "0 16 * * *"
jobs:
  build_vplus:
    uses: codercaizh/openwrt_package/.github/workflows/build.yml@master
    with:
      target: 'vplus'
      config: 'armv8'
  build_n1:
    uses: codercaizh/openwrt_package/.github/workflows/build.yml@master
    with:
      target: 's905d'
      config: 'armv8_full'
