name: Openwrt Build Schedule
on:
  workflow_dispatch: 
  schedule:
    - cron: "0 16 * * *"
jobs:
  x86:
    uses: codercaizh/openwrt_package/.github/workflows/build.yml@master
    with:
      target: 'x86'
      config: 'x86_64'
  vplus:
    uses: codercaizh/openwrt_package/.github/workflows/build.yml@master
    with:
      target: 'vplus'
      config: 'armv8'
  n1:
    uses: codercaizh/openwrt_package/.github/workflows/build.yml@master
    with:
      target: 's905d'
      config: 'armv8_full'
  r3g:
    uses: codercaizh/openwrt_package/.github/workflows/build.yml@master
    with:
      target: 'r3g'
      config: 'r3g'
  rm2100:
    uses: codercaizh/openwrt_package/.github/workflows/build.yml@master
    with:
      target: 'rm2100'
      config: 'rm2100'
