name: Openwrt Build Schedule
on:
  workflow_dispatch: 
    inputs:
      upgrade: 
          description: '完成后更新版本文件'
          required: true
          type: boolean
          default: true
  schedule:
    - cron: "0 16 * * *"
jobs:
  x86:
    uses: codercaizh/openwrt_package/.github/workflows/build.yml@master
    with:
      target: 'x86'
      config: 'x86_64'

  vplus:
    uses: codercaizh/openwrt_package/.github/workflows/build.yml@master
    with:
      target: 'vplus'
      config: 'armv8'

  n1:
    uses: codercaizh/openwrt_package/.github/workflows/build.yml@master
    with:
      target: 's905d'
      config: 'armv8_full'

  r3g:
    uses: codercaizh/openwrt_package/.github/workflows/build.yml@master
    with:
      target: 'r3g'
      config: 'r3g'

  rm2100:
    uses: codercaizh/openwrt_package/.github/workflows/build.yml@master
    with:
      target: 'rm2100'
      config: 'rm2100'

  upgrade:
    if: inputs.upgrade
    needs: [x86, vplus, n1, r3g, rm2100]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Upgrade version
        run: |
          echo "#!/bin/bash\n# 此文件用于配置编译时使用的openwrt源码版本以及插件版本，若没有配置或文件不存着，在默认使用最新的代码编译\n# 问：为什么要有这个版本号机制而不是默认就使用最新版本编译\n# 答：由于OP和插件源码更新非常频繁，部分更新可能会导致编译失败，所以需要有一个Release的版本机制，记录百分百能够编出来的版本\n >> version.sh
          echo "OPENWRT_VER=${{ needs.x86.outputs.OPENWRT_VER }}" >> version.sh
          echo "OPENWRT_COMMIT_ID=${{ needs.x86.outputs.OPENWRT_COMMIT_ID }}" >> version.sh
          echo "OPENWRT_PACKAGES_COMMIT_ID=${{ needs.x86.outputs.OPENWRT_PACKAGES_COMMIT_ID }}" >> version.sh
          echo "PASSWALL_PACKAGE_COMMIT_ID=${{ needs.x86.outputs.PASSWALL_PACKAGE_COMMIT_ID }}" >> version.sh
          echo "SMALL_PACKAGE_COMMIT_ID=${{ needs.x86.outputs.SMALL_PACKAGE_COMMIT_ID }}" >> version.sh
          git config user.name robot
          git config user.email 545347837@qq.com
          git add .
          git commit -m "ypgrade version to ${{ needs.x86.outputs.OPENWRT_VER }}"
          git push


