name: Openwrt Build Schedule
on:
  workflow_dispatch: 
  schedule:
    - cron: "22 17 * * *"
jobs:
    name: Openwrt Build Schedule
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout package script
          uses: actions/checkout@v2.5.0
          with:
            path: package_scirpt

        - name: Build openwrt
            run: sudo bash $PWD/scripts/schedule_package.sh $PWD/output ${{ secrets.PUSH_TOKEN }}
            working-directory: package_scirpt

        - name: Set artifact
            run: |
              ARTIFACT_PATH=$(ls $PWD/output/*)
              echo "ARTIFACT_PATH=$ARTIFACT_PATH" >> $GITHUB_ENV
              echo "ARTIFACT_DIR=$(basename $ARTIFACT_PATH)" >> $GITHUB_ENV
            working-directory: package_scirpt

        - name: Upload artifact
            uses: actions/upload-artifact@v3.1.1
            with:
              name: schedule_build_${{ env.ARTIFACT_DIR }}.zip
              path: ${{ env.ARTIFACT_PATH }}
              retention-days: 2

