name: Openwrt Build Schedule
on:
  workflow_dispatch: 
jobs:
  build:
    name: Schedule Openwrt Build
    runs-on: self-hosted
    steps:
      - name: Clean source
        run: sudo rm -rf ./source

      - name: Clean environment
        if:  ${{ !inputs.useCache }} 
        run: sudo rm -rf ./compile_dir

      - name: Checkout source
        uses: actions/checkout@v2.5.0
        with:
          path: source

      - name: Set use latest
        if:  ${{ inputs.useLatestCode }} 
        run: sudo rm -rf version.sh
        working-directory: source

      - name: Build openwrt
        run: sudo ./run_build_use_docker.sh -c ${{ inputs.config }} -d ${{ inputs.target }} -n "GithubActionBuild_${{ github.run_number }}" -o ${{ github.workspace }}/compile_dir
        working-directory: source

          - name: Upload artifact
            uses: actions/upload-artifact@v3.1.1
            with:
              name: schedule_build_$(TZ=':Asia/Shanghai' date '+%y.%m.%d')
              path: package_scirpt/openwrt_build_tmp/artifact
              retention-days: 3