name: test
on:
  workflow_dispatch: 
jobs:
  example_matrix:
    strategy:
      matrix:
        include:
          - target: 'x86'
            config: 'x86_64'
          - target: "r3g"
            config: "r3g"
    uses: codercaizh/openwrt_package/.github/workflows/build.yml@master
    with:
      target: ${{ matrix.target }}
      config: ${{ matrix.config }}
