name: test_sub
on:
  workflow_dispatch: 
  workflow_call: 
    outputs:
      oo1:
        description: "The first output string"
        value: ${{ jobs.test.outputs.o1 }}
      oo2:
        description: "The second output string"
        value: ${{ jobs.test.outputs.o2 }}
jobs:
  test:
    runs-on: ubuntu-latest
    outputs: 
      o1: ${{ steps.s1.outputs.var1 }} 
      o2: ${{ steps.s1.outputs.var2 }} 
    steps:
      - id: s1
        run: |
          echo "var1=hello" >> $GITHUB_OUTPUT
          echo "var2=world" >> $GITHUB_OUTPUT
 
