name: test
on:
  workflow_dispatch: 
jobs:
  example_matrix:
    strategy:
      matrix:
        include:
          - target: 'x86'
            config: 'x86_64'
          - target: "r3g"
            config: "r3g"
    uses: codercaizh/openwrt_package/.github/workflows/test_sub.yml@master
    with:
      target: ${{ matrix.target }}
      config: ${{ matrix.config }}
  show:
    needs: [example_matrix]
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Print input
        run:  |
          echo "${{ toJSON(needs) }}"
