name: test_sub
on:
  workflow_dispatch: 
  workflow_call: 
    inputs:
      target:
        required: true
        type: string
    outputs:
      oo1:
        description: "The first output string"
        value: ${{ jobs.test.outputs.o1 }}
jobs:
  test:
    runs-on: ubuntu-latest
    outputs: 
      o1: ${{ steps.s1.outputs.var1 }} 
    steps:
      - id: s1
        run: |
          echo "var1=${{ inputs.target }}" >> $GITHUB_OUTPUT
 
