name: test
on:
  workflow_dispatch: 
jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ github.event.client_payload.versions }}
        include:
          - target: 'x86'
            config: 'x86_64'
          - target: "r3g"
            config: "r3g"
    uses: codercaizh/openwrt_package/.github/workflows/build.yml@master
    with:
      target: ${{ matrix.target }}
      config: ${{ matrix.r3g }}